Lecture03
sasamuraso/Raise-git pull request #5
Opened 2023-05-09 16:05 UTC by sasamuraso

第3回課題

2023-05-09 16:25 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！

2023-05-09 16:25 UTC, MasatoshiMizumoto commented on lecture03.md
> +**・Puma、mysql共に再起動するとアプリケーションページは正常に表示される。**
この書き方ですが、番号無しリストなのかボールド体なのか、どうしたいのかが読みにくいので、Markdown記法について調査いただいたあと変えて欲しいです！

2023-05-09 16:25 UTC, MasatoshiMizumoto commented on lecture03.md
> +[app画面.png](./image/Lecture03/L3_l3app.png "app画面.png")
せっかく画像なのでaタグよりimgタグで処理される記法が良いかなと思います！

2023-05-09 16:59 UTC, sasamuraso commented
ご確認ありがとうございます。
全体のレイアウトと指摘いただいたボールド体は通常の文字に戻しました。
また、画像もimgタグに変更いたしました。
よろしくお願いします。

2023-05-09 17:23 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-05-09 17:23 UTC, MasatoshiMizumoto commented on lecture03.md
> +本レクチャーではPumaを使用していた。<br>
```suggestion
- APサーバーはアプリケーションを動作させるためのサーバー。
- 本レクチャーではPumaを使用していた。
```

markdownの段落（何も修飾しない書き方）は改行がないので、こまめに改行をしたいときはリスト表記にするのが良いかなと思います！

2023-05-09 17:23 UTC, MasatoshiMizumoto commented on lecture03.md
> +4. bin/devでアプリケーション起動<br>
番号付きリストは改行コード要らないです！

2023-05-09 17:23 UTC, MasatoshiMizumoto commented on lecture03.md
> +**・bundle exec rails db:create**<br>
中点はMarkdownのリスト記号と誤読しやすいので先頭に置くのは避けてほしいです！
現場でも恐らく同じ指摘を受けると思います！

2023-05-10 05:21 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-05-12 04:14 UTC, merged