第4回課題
sasamuraso/Raise-git pull request #6
Opened 2023-05-14 04:01 UTC by sasamuraso

第4回課題になります。よろしくお願いします。

2023-05-14 08:10 UTC, MasatoshiMizumoto requested changes
imgタグ部分コメント入れてますのでご対応ください！

2023-05-14 08:10 UTC, MasatoshiMizumoto commented on lecture04.md
> +<img src="image/Lecture04/VPC.png" width="700" />
imgタグに相当するmarkdown記述があるのでそっちにしてください！
他の部分も同様です！

2023-05-14 08:10 UTC, MasatoshiMizumoto commented on lecture04.md
> ++ OSはAmazon Linux 2023
2023は随分仕様が変わってますので、講師メンター陣にナレッジがなく質問対応が遅れるかもです、ご容赦ください:pray:

2023-05-15 09:01 UTC, sasamuraso commented on lecture04.md
> +<img src="image/Lecture04/VPC.png" width="700" />
あまりHTMLとMarkdownは混合して使われることはないのですか？

2023-05-15 09:01 UTC, sasamuraso commented on lecture04.md
> ++ OSはAmazon Linux 2023
詰まった時点でAmazonLinux 2に変更する準備はできています。😆

2023-05-15 09:29 UTC, MasatoshiMizumoto commented on lecture04.md
> +<img src="image/Lecture04/VPC.png" width="700" />
はい、基本的には無いですね！

2023-05-15 09:29 UTC, MasatoshiMizumoto commented on lecture04.md
> ++ OSはAmazon Linux 2023
了解です！

2023-05-15 09:30 UTC, MasatoshiMizumoto approved these changes
LGTM!
マージして次の課題にすすんでください！

2023-05-15 09:38 UTC, merged